# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# Creatin Arrays

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10)

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(10,10)

array([], dtype=int32)

In [19]:
np.arange(-1000,1000)

array([-1000,  -999,  -998, ...,   997,   998,   999])

In [20]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
zero=np.zeros([2,2])
type(zero)

numpy.ndarray

In [26]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
n=(6,7)
n1=(6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [28]:
print(np.zeros(n1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [29]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [30]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
range(5)

range(0, 5)

In [32]:
r=range(5)
r

range(0, 5)

In [33]:
for i in r:
    print(i)

0
1
2
3
4


In [34]:
list(range(5))
[0,1,2,3,4]
     

[0, 1, 2, 3, 4]

In [35]:
list(range(5))
[0,1,2,3,4]

[0, 1, 2, 3, 4]

In [36]:
range(1,10)

range(1, 10)

In [37]:
list(range(1,10))


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
list(range(1,20,3))

[1, 4, 7, 10, 13, 16, 19]

In [40]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [41]:
np.random.rand(3,2)

array([[0.28718124, 0.24988118],
       [0.79523383, 0.55934544],
       [0.99148995, 0.99259113]])

In [42]:
np.random.rand(4)

array([0.89483186, 0.42033695, 0.99410799, 0.42576254])

In [44]:
np.random.rand(3,6)

array([[0.11635698, 0.19457403, 0.01954021, 0.67363637, 0.02067767,
        0.34568781],
       [0.46227536, 0.80315852, 0.66890588, 0.29781105, 0.03632532,
        0.82963004],
       [0.45388837, 0.12655784, 0.5899013 , 0.34190246, 0.68166773,
        0.13980535]])

In [45]:
np.random.randint(2,4)

3

In [46]:
np.random.randint(3,79)

73

In [47]:
np.random.randint(0,1)

0

In [48]:
np.random.randint(1,2,3)

array([1, 1, 1])

In [49]:
np.random.randint(1)

0

In [50]:
np.random.randint(10,21,3)

array([12, 16, 15])

In [52]:
np.random.randint(1,12,10)

array([ 5,  9,  9, 10,  7,  4,  8,  5,  9,  4])

In [53]:
np.random.randint(10,40,(10,10))

array([[17, 31, 29, 25, 13, 20, 15, 33, 27, 12],
       [36, 21, 22, 16, 11, 38, 13, 15, 23, 36],
       [17, 16, 19, 12, 30, 32, 31, 18, 12, 23],
       [17, 28, 33, 30, 20, 22, 28, 11, 21, 29],
       [14, 13, 34, 12, 23, 25, 11, 16, 36, 27],
       [12, 30, 12, 19, 29, 33, 21, 30, 33, 12],
       [34, 27, 33, 15, 25, 21, 13, 29, 25, 33],
       [17, 17, 22, 29, 22, 18, 20, 15, 32, 12],
       [32, 19, 36, 27, 21, 21, 25, 23, 33, 30],
       [20, 14, 19, 33, 22, 26, 25, 15, 14, 36]])

In [54]:
b=np.random.randint(10,20,(5,4))
b

array([[18, 10, 17, 19],
       [17, 12, 15, 16],
       [11, 13, 19, 16],
       [16, 14, 15, 16],
       [18, 16, 12, 18]])

# ":"- is used for slicing,we need to

provide rows and columns among the slicing point

In [55]:
b[:]

array([[18, 10, 17, 19],
       [17, 12, 15, 16],
       [11, 13, 19, 16],
       [16, 14, 15, 16],
       [18, 16, 12, 18]])

In [56]:
b[0:-1]

array([[18, 10, 17, 19],
       [17, 12, 15, 16],
       [11, 13, 19, 16],
       [16, 14, 15, 16]])

# "," is used to get specific indexing number

In [57]:
b[0,2]

17

In [58]:
np.random.randint(10,20,(4,4))

array([[19, 10, 14, 19],
       [19, 16, 18, 18],
       [17, 17, 12, 11],
       [15, 10, 19, 14]])

# Operation

In [59]:
a=np.random.randint(10,20,5)
a

array([16, 13, 17, 18, 13])

In [60]:
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr2=np.random.randint(0,100,(100,10))
arr2

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [62]:
arr

array([0, 1, 2, 3, 4, 5])

In [63]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [64]:
arr[:4]

array([0, 1, 2, 3])

In [65]:
arr2[:]

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [66]:
arr2[0:6]

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87]])

In [67]:
arr2[1,9]

28

In [68]:
arr2

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [69]:
arr2[-7,7]

92

In [70]:
arr2[-7,-7]

80

In [71]:
arr2

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [72]:
arr2[::-1]

array([[67, 23, 76,  7, 42, 83,  8, 51, 47, 90],
       [38, 86, 34, 18, 27, 48, 68, 93, 14, 37],
       [38, 99, 44, 43, 38,  3, 18,  0, 53, 81],
       [ 1, 76, 12, 71, 23, 17, 23, 34,  0, 37],
       [97, 12, 42, 54, 12, 75, 26, 57, 63, 43],
       [58, 12, 19, 81, 53, 61, 48, 55, 41, 60],
       [78, 42, 13, 80, 86, 12, 81, 92,  9, 45],
       [69, 52, 69, 82, 25, 22, 68, 83, 57, 69],
       [12, 85, 98, 44,  4, 97, 28, 47, 87, 78],
       [37, 75, 31, 81, 19,  1, 38, 61, 47, 85],
       [ 2, 56, 78, 54, 83, 78, 72, 90, 26, 68],
       [59, 73, 95, 84, 13, 76, 72,  8,  7, 23],
       [75, 32, 41, 27, 71, 45, 85, 21, 69, 97],
       [70, 26, 99, 18, 90, 62, 13, 29, 43, 12],
       [43, 65, 59, 23, 19, 90,  3, 37, 85, 56],
       [51, 28, 97,  8, 95, 99, 16,  9, 54, 40],
       [19, 75, 21, 53, 32, 11, 75, 13, 77, 92],
       [72, 62, 17, 14, 38, 94, 22, 32, 81, 17],
       [77, 12, 20,  4, 61, 27,  4, 65, 98, 42],
       [53, 74, 73, 46,  6, 59, 68, 75, 52, 46],
       [81,  5, 24, 

In [73]:
arr2

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [74]:
arr2[::-2]

array([[67, 23, 76,  7, 42, 83,  8, 51, 47, 90],
       [38, 99, 44, 43, 38,  3, 18,  0, 53, 81],
       [97, 12, 42, 54, 12, 75, 26, 57, 63, 43],
       [78, 42, 13, 80, 86, 12, 81, 92,  9, 45],
       [12, 85, 98, 44,  4, 97, 28, 47, 87, 78],
       [ 2, 56, 78, 54, 83, 78, 72, 90, 26, 68],
       [75, 32, 41, 27, 71, 45, 85, 21, 69, 97],
       [43, 65, 59, 23, 19, 90,  3, 37, 85, 56],
       [19, 75, 21, 53, 32, 11, 75, 13, 77, 92],
       [77, 12, 20,  4, 61, 27,  4, 65, 98, 42],
       [81,  5, 24, 34, 61, 61, 52, 92,  0,  4],
       [42, 89, 77, 45, 60, 20, 56, 72, 12, 41],
       [ 6, 47, 49, 58, 46, 95, 39, 40, 15, 27],
       [15, 17, 82, 40, 79, 33, 90, 60, 53, 89],
       [92, 60, 32, 16, 72, 92, 53, 69, 15, 95],
       [36, 40, 53, 80, 81, 21, 36, 21, 73, 42],
       [58,  3,  7, 24, 50, 45, 99, 76, 93, 21],
       [95,  0, 54, 85, 97, 79, 64, 60, 62, 71],
       [38, 23, 26, 73, 22, 20, 35, 21,  1, 43],
       [10, 56, 33, 52, 46, 92, 60, 62, 69, 41],
       [53, 41, 27, 

In [75]:
arr2

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [97, 29, 81, 33, 11, 57, 53,  4, 21, 28],
       [89, 19,  8, 62, 37, 97,  0, 12, 35, 94],
       [86, 65, 80, 27, 56, 17, 30, 43, 74, 57],
       [ 6, 32, 51, 47, 59, 17,  8, 43, 14, 57],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [18, 64, 47, 27, 48, 51, 95,  7, 99, 81],
       [23, 51, 75, 53, 85, 12, 56, 68, 60, 12],
       [59, 41, 62, 30, 53, 17, 97, 92, 42, 94],
       [75, 91, 11, 80, 20, 67, 48, 68, 62, 16],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [27, 52, 84, 29,  0,  8, 85, 61, 78, 96],
       [ 6, 69, 28, 60, 32, 93, 22, 44, 41, 66],
       [87, 23, 53, 27, 22,  8,  8, 80,  4, 52],
       [57,  8, 99,  7, 70, 40, 43, 65, 43, 94],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [85, 23, 72, 73, 50, 70, 73, 73, 70,  9],
       [11, 21, 74, 55, 23, 66, 19, 43, 57,  1],
       [20, 73, 85, 33, 83, 66, 10, 46, 28, 93],
       [75,  4, 18, 38, 58, 21, 36, 85, 98, 18],
       [31, 19, 44, 

In [76]:
arr2[::5]

array([[49,  7, 72, 10, 63, 33, 75, 21, 69, 85],
       [11, 61, 20, 56, 93,  9,  6, 29, 26, 87],
       [93, 19, 75, 55, 87, 94, 89, 35, 20, 83],
       [14, 44, 31, 46, 41, 42,  2, 16, 23, 32],
       [31, 19, 44, 22, 14, 93,  9, 43, 76, 52],
       [27, 33, 79, 30, 70, 25, 11, 99, 75, 88],
       [37, 79,  2, 77, 72, 96, 41, 96, 60, 53],
       [40, 67, 20, 78, 99, 12,  3, 81,  8,  1],
       [75, 66, 46,  5, 49, 51, 10, 31, 62, 97],
       [68, 30, 91, 90, 94, 38, 30, 34, 62, 34],
       [71, 79, 79, 39, 68, 86, 32, 92, 66, 60],
       [80, 37, 86, 85, 85, 41,  1, 23, 14, 70],
       [ 2, 25, 45, 62,  8, 80, 23, 33, 66, 74],
       [95,  0, 54, 85, 97, 79, 64, 60, 62, 71],
       [54, 75, 80, 78, 88, 27, 41, 77, 44, 84],
       [ 6, 47, 49, 58, 46, 95, 39, 40, 15, 27],
       [53, 74, 73, 46,  6, 59, 68, 75, 52, 46],
       [43, 65, 59, 23, 19, 90,  3, 37, 85, 56],
       [37, 75, 31, 81, 19,  1, 38, 61, 47, 85],
       [97, 12, 42, 54, 12, 75, 26, 57, 63, 43]])

In [77]:
arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr.max()

5

In [79]:
arr.max()


5

In [80]:
arr.min()

0

In [81]:
arr.mean()

2.5

In [84]:
from numpy import *
a = array([1,2,3,4,9])
median(a)



3.0

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [90]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [91]:
arr

array([0, 1, 2, 3, 4, 5])

# Only three type of orders are there in reshape C- Type F- Type A- Type

C type indexing order

In [94]:
arr.reshape(3,2,order='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

F- fortran indexing ordr

In [96]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [97]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [98]:
array([[0,2,4],[1,3,5]])

array([[0, 2, 4],
       [1, 3, 5]])

A-Arbitary indexing order

In [99]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [102]:
arr.reshape(6,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [103]:
arr

array([0, 1, 2, 3, 4, 5])

In [104]:
arr.shape

(6,)

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [109]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [110]:
row=4
col=5

In [111]:
col

5

In [112]:
row

4

In [113]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [114]:
mat[row,col]

45

In [115]:
mat[4,5]

45

In [116]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
col=6

In [119]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [121]:
row

4

In [122]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [123]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [125]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [126]:
row

4

In [127]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [128]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [129]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [130]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
row

4

In [133]:
col

6

In [134]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [136]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
mat[1,4]

14

In [138]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[3,-3]

37

In [140]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [143]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [146]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [147]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [148]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [150]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [152]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [153]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [154]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [155]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [156]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [157]:
mat[1:2,2:4]

array([[12, 13]])

In [158]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
mat[2:3,4:5]

array([[24]])

# Masking also called as Filter

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
id(mat)

2557987032688

In [163]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [164]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [165]:
mat[mat==50]

array([50])

In [167]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [169]:
a2=mat[mat<50]
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [170]:
a3=mat[mat==50]
a3

array([50])

In [171]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [173]:
a3

array([50])